### ISSUE TITLE
Update the CLI to handle DeleteStudy and DeleteSeries methods in v1 branch

### ISSUE THREAD

**Issue by danielbeaudreau** [GoogleCloudPlatform/healthcare-api-dicomweb-cli#51]
These methods now return a long running operation. We should verify that this does not break the CLI, and update it if it does.

**Comment by pavertomato** [comment]
> We should verify that this does not break the CLI, and update it if it does.

cli works fine with DeleteStudy and DeleteSeries, since they still return 200, but does not print id of operation, should we update cli to print it into console?

**Comment by dzelemba** [comment]
Ideally the tool would poll the ID until the deletion request is complete.

**Comment by pavertomato** [comment]
> Ideally the tool would poll the ID until the deletion request is complete.

it's quite simple, but since operation is requested by different url we'll need to parse host parameter, or split it to few new params. can we guarantee what healthcare API url always ends with "projects/<project_id>/locations/<location_id>/datasets/<dataset_id>/dicomStores/<dicom_store_id>/dicomWeb" pattern? or some different pattern to make parsing optional and tool compatible with other dicomweb services?

**Comment by dzelemba** [comment]
Or you could parse the HTTP response to determine what the response is? This way we wouldn't need any code updates once this makes it to beta and alpha.

**Comment by pavertomato** [comment]
> Or you could parse the HTTP response to determine what the response is? This way we wouldn't need any code updates once this makes it to beta and alpha.

my concern is not determination if long running is present, it's quite simple - if we have "name" in response body then we concat it to host string.
and here is my concern - we can't just concat if we use reverse proxy(as in https://github.com/mukhlin/dicom-api-cache) or some alternative instance(as you use in dev as i understand) it could hide part of url and if we try to cut off something like "projects/<project_id>/locations/<location_id>/datasets/<dataset_id>/dicomStores/<dicom_store_id>/dicomWeb"  we'll get incorrect url

**Comment by dzelemba** [comment]
Aha got it. Good point. In that case, let's just do the best we can. If we can successfully parse the dicomweb_url, then we can automatically wait on the operation otherwise we can just print out the operation ID. The delete methods are healthcare API specific feature anyways, so probably wouldn't work in other archives. If someone is using the cache then ya there isn't much we can do besides print the ID.
